[package]
name = "ferr_os"
version = "0.1.0"
authors = ["William Walcher <wjwalcher@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.6.0"
volatile = "0.2.3"
spin = "0.4.9"
cpuio = "0.2.0"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]